name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24


      - name: Install and Build
        run: |
          npm i -g pnpm
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./dist
